const MIN_WIDTH = 100;
const MIN_HEIGHT = 30;
const DEFAULT_OPACITY = 0.85;
const DEFAULT_COLOR = '#000000';
const DEFAULT_BLUR = 0;
const MAX_BLUR = 40;
const DEFAULT_WIDTH = 800;
const DEFAULT_HEIGHT = 100;
const DEFAULT_BOTTOM_OFFSET = 80;

const MSG = {
  TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY',
  UPDATE_BLOCKER: 'UPDATE_BLOCKER',
  SET_OPACITY: 'SET_OPACITY',
  SET_COLOR: 'SET_COLOR',
  SET_BLUR: 'SET_BLUR',
  GET_STATE: 'GET_STATE',
  PING: 'PING',
};
