const MIN_WIDTH = 100;
const MIN_HEIGHT = 30;
const DEFAULT_OPACITY = 0;
const DEFAULT_COLOR = '#000000';
const DEFAULT_BLUR = 6;
const DEFAULT_WIDTH = 800;
const DEFAULT_HEIGHT = 100;
const DEFAULT_BOTTOM_OFFSET = 80;

const MSG = {
  TOGGLE_VISIBILITY: 'TOGGLE_VISIBILITY',
  UPDATE_BLOCKER: 'UPDATE_BLOCKER',
  SET_OPACITY: 'SET_OPACITY',
  SET_COLOR: 'SET_COLOR',
  SET_BLUR: 'SET_BLUR',
  GET_STATE: 'GET_STATE',
};

const MODE_PER_TAB = 'per-tab';
const MODE_GLOBAL = 'global';
const DEFAULT_VISIBILITY_MODE = MODE_PER_TAB;

const DEFAULT_FEATHER_EDGES = false;
